name: torch-12.4
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - anyio=4.10.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - attrs=25.4.0
  - beautifulsoup4=4.14.2
  - bleach=6.3.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cffi=2.0.0
  - colorama=0.4.6
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - html5lib=1.1
  - idna=3.11
  - ipykernel=6.31.0
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - libexpat=2.7.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.1
  - parso=0.8.5
  - pip=25.3
  - platformdirs=4.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=4.0.0
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - referencing=0.37.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.28.0
  - send2trash=1.8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.51.0
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - winpty=0.4.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - filelock==3.20.0
      - fsspec==2025.12.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - pillow==12.0.0
      - ruff==0.14.10
      - sympy==1.14.0
      - torch==2.4.0+cu124
      - torchaudio==2.4.0+cu124
      - torchvision==0.19.0+cu124

